-- Snapshot of public club facts from findapadelcourt.co.za.
-- Names, places, and court counts only. Their venue descriptions are not copied.
insert into public.clubs (id, name, suburb, city, province, court_count, booking_platform)
values
  ('beacon-bay-padel', 'Beacon Bay Padel', 'Beacon Bay', 'East London', 'Eastern Cape', 4, 'Playtomic'),
  ('padel-park-east-london', 'Padel Park East London', null, 'East London', 'Eastern Cape', 2, 'Playtomic'),
  ('new-era-padel', 'New Era Padel', null, 'Gqeberha', 'Eastern Cape', 4, 'Playtomic'),
  ('old-grey-padel', 'Old Grey Padel', null, 'Gqeberha', 'Eastern Cape', 2, 'Playtomic'),
  ('pitch-n-padel', 'Pitch n Padel', null, 'Gqeberha', 'Eastern Cape', 2, 'Playtomic'),
  ('sunridge-action-arena', 'Sunridge Action Arena', 'Sunridge', 'Gqeberha', 'Eastern Cape', 1, 'Playtomic'),
  ('techno-padel-walmer', 'Techno Padel Walmer', 'Walmer', 'Gqeberha', 'Eastern Cape', 3, 'Playtomic'),
  ('trend-entertainment-centre', 'Trend Entertainment Centre', null, 'Gqeberha', 'Eastern Cape', 2, 'Playtomic'),
  ('virgin-active-padel-lorraine', 'Virgin Active Padel Lorraine', 'Lorraine', 'Gqeberha', 'Eastern Cape', 2, 'Playtomic'),
  ('walmer-padel', 'Walmer Padel', 'Walmer', 'Gqeberha', 'Eastern Cape', null, 'Playtomic'),
  ('africa-padel-bloemfontein', 'Africa Padel Bloemfontein', null, 'Bloemfontein', 'Free State', 4, 'Playtomic'),
  ('net-set-ramblers-club', 'Net Set Ramblers Club', null, 'Bloemfontein', 'Free State', null, 'Playtomic'),
  ('padel-in-the-woods', 'Padel in the Woods', null, 'Bloemfontein', 'Free State', null, 'Playtomic'),
  ('padelworx', 'PadelWorx', null, 'Bloemfontein', 'Free State', null, 'Playtomic'),
  ('anglowealth-country-club', 'Anglowealth Country Club', null, 'Centurion', 'Gauteng', 4, 'Playtomic'),
  ('gayle-nexia', 'Gayle @ Nexia', null, 'Centurion', 'Gauteng', 2, 'Playtomic'),
  ('gayle-padel-lenasia', 'Gayle Padel Lenasia', 'Lenasia', 'Centurion', 'Gauteng', 2, 'Playtomic'),
  ('padel-al-asr', 'Padel @ Al-Asr', 'Centurion', 'Centurion', 'Gauteng', 3, 'Playtomic'),
  ('proactive-padel-irene', 'Proactive Padel Irene', 'Doringkloof', 'Centurion', 'Gauteng', 4, 'Playtomic'),
  ('raslouw-corner-padel-club', 'Raslouw Corner Padel Club', 'Raslouw', 'Centurion', 'Gauteng', 4, 'Playtomic'),
  ('rooftop-padel-centurion', 'Rooftop Padel Centurion', 'Centurion', 'Centurion', 'Gauteng', 2, 'Playtomic'),
  ('top-padel-zwartkop', 'Top Padel Zwartkop', 'Zwartkop', 'Centurion', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-dunkeld', 'Africa Padel Dunkeld', 'Dunkeld', 'Johannesburg', 'Gauteng', 5, 'Playtomic'),
  ('africa-padel-german-country-club', 'Africa Padel German Country Club', 'Sandton', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-glenvista', 'Africa Padel Glenvista', 'Glenvista', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-old-park', 'Africa Padel Old Park', null, 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-royal-johannesburg', 'Africa Padel Royal Johannesburg', null, 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('africa-padel-ruimsig', 'Africa Padel Ruimsig', 'Ruimsig', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-sandton', 'Africa Padel Sandton', 'Sandton', 'Johannesburg', 'Gauteng', 6, 'Playtomic'),
  ('africa-padel-three-rivers', 'Africa Padel Three Rivers', 'Three Rivers', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('club-padel-morningside', 'Club Padel Morningside', 'Morningside', 'Johannesburg', 'Gauteng', 5, 'Playtomic'),
  ('clubpadel-pirates', 'ClubPadel Pirates', 'Greenside', 'Johannesburg', 'Gauteng', 5, 'Playtomic'),
  ('crystal-padel-randburg', 'Crystal Padel Randburg', 'Randburg', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('epic-padel-huddle-park', 'Epic Padel Huddle Park', 'Linksfield', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('ijump-clearwater-mall', 'iJump Clearwater Mall', 'Roodepoort', 'Johannesburg', 'Gauteng', null, 'Direct'),
  ('indoor-padel-revolution', 'Indoor Padel Revolution', 'Honeydew', 'Johannesburg', 'Gauteng', 7, 'Playtomic'),
  ('jogo-padel-honeydew', 'Jogo Padel Honeydew', 'Honeydew', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('johannesburg-country-club', 'Johannesburg Country Club', 'Auckland Park', 'Johannesburg', 'Gauteng', 3, 'Direct (members)'),
  ('jozi-padel-sandton', 'Jozi Padel Sandton', 'Sandton', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('liv-padel-supersport-park', 'Liv Padel Supersport Park', 'Midrand', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('marks-park-padel', 'Marks Park Padel', 'Randburg', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('match-padel-fourways', 'Match Padel Fourways', 'Fourways', 'Johannesburg', 'Gauteng', 8, 'Playtomic'),
  ('moove-fitness-padel', 'Moove Fitness Padel', 'Alexandra', 'Johannesburg', 'Gauteng', 1, 'Direct'),
  ('n12-padel-boksburg', 'N12 Padel Boksburg', 'Boksburg', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('net-set-padel-sandton-city', 'Net Set Padel Sandton City', 'Sandton', 'Johannesburg', 'Gauteng', 8, 'Playtomic'),
  ('net-set-padel-sandton-city-rooftop', 'Net Set Padel Sandton City Rooftop', 'Sandton', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('padel-co-rietvlei', 'Padel & Co Rietvlei', 'Alberton', 'Johannesburg', 'Gauteng', 6, 'Playtomic'),
  ('padel-365-greenstone', 'Padel 365 Greenstone', 'Greenstone', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('padel-active-boksburg', 'Padel Active Boksburg', 'Boksburg', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('padel-and-social-club-gray-park', 'Padel and Social Club Gray Park', 'Melrose', 'Johannesburg', 'Gauteng', null, 'Playtomic'),
  ('padel-and-social-club-melrose', 'Padel and Social Club Melrose', 'Melrose', 'Johannesburg', 'Gauteng', null, 'Playtomic'),
  ('padel-clear-water-crossing', 'Padel Clear Water Crossing', 'Roodepoort', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('padel-farm-ruimsig', 'Padel Farm Ruimsig', 'Ruimsig', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('padel-lab-rivonia-recreation-club', 'Padel Lab Rivonia Recreation Club', 'Rivonia', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('padel-lab-ruimsig', 'Padel Lab Ruimsig', 'Ruimsig', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('padel-perfect-erand-gardens', 'Padel Perfect Erand Gardens', 'Midrand', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('padel-plus-benoni-country-club', 'Padel Plus Benoni Country Club', 'Benoni', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('padel-quip-old-bens-club', 'Padel Quip Old Bens Club', 'Benoni', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('padel-resort-waterfall', 'Padel Resort Waterfall', 'Waterfall', 'Johannesburg', 'Gauteng', null, 'Playtomic'),
  ('padel-vibe-kyalami', 'Padel Vibe Kyalami', 'Kyalami', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('padel-xtreme-midrand', 'Padel Xtreme Midrand', 'Midrand', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('propadel-craighall', 'ProPadel Craighall', 'Craighall', 'Johannesburg', 'Gauteng', 5, 'Playtomic'),
  ('propadel-greek-club', 'ProPadel Greek Club', 'Germiston', 'Johannesburg', 'Gauteng', 6, 'Playtomic'),
  ('qurtuba-padel-tennis', 'Qurtuba Padel Tennis', 'Sandton', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('rbclub-melrose-arch', 'RBClub Melrose Arch', 'Melrose Arch', 'Johannesburg', 'Gauteng', 8, 'Playtomic'),
  ('ridgepark-sports-club', 'Ridgepark Sports Club', 'Turfontein', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('rivonia-padel', 'Rivonia Padel', 'Sandton', 'Johannesburg', 'Gauteng', 1, 'Playtomic'),
  ('steyn-city-padel', 'Steyn City Padel', 'Sandton', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('ten-by-twenty-killarney', 'Ten By Twenty Killarney', 'Killarney', 'Johannesburg', 'Gauteng', 7, 'Playtomic'),
  ('ten-by-twenty-lenasia', 'Ten By Twenty Lenasia', 'Lenasia', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('thaba-sports-centre-mulbarton', 'Thaba Sports Centre Mulbarton', 'Mulbarton', 'Johannesburg', 'Gauteng', 2, 'Playtomic'),
  ('the-emerald-sky-padel', 'The Emerald Sky Padel', 'Sandton', 'Johannesburg', 'Gauteng', 1, 'Playtomic'),
  ('the-padel-bar-and-cafe-glendower', 'The Padel Bar and Cafe @ Glendower', 'Glendower', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('the-wanderers-club', 'The Wanderers Club', 'Illovo', 'Johannesburg', 'Gauteng', 6, 'Playtomic'),
  ('top-padel-alberton', 'Top Padel Alberton', 'Alberton', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('virgin-active-padel-bedfordview', 'Virgin Active Padel Bedfordview', 'Bedfordview', 'Johannesburg', 'Gauteng', 3, 'Playtomic'),
  ('virgin-active-padel-huddle-park', 'Virgin Active Padel Huddle Park', 'Linksfield', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('virgin-active-padel-old-eds', 'Virgin Active Padel Old Eds', 'Linksfield', 'Johannesburg', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-brooklyn', 'Africa Padel Brooklyn', 'Brooklyn', 'Pretoria', 'Gauteng', 4, 'Playtomic'),
  ('africa-padel-olympus', 'Africa Padel Olympus', 'Olympus', 'Pretoria', 'Gauteng', 5, 'Playtomic'),
  ('ballers-padel-arena', 'Ballers Padel Arena', 'Mountain Lake', 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('balwin-padel-thaba', 'Balwin Padel Thaba', 'Centurion', 'Pretoria', 'Gauteng', 6, 'Playtomic'),
  ('centre-court-padel-lynnwood', 'Centre Court Padel Lynnwood', 'Lynnwood Glen', 'Pretoria', 'Gauteng', 1, 'Playtomic'),
  ('dpt-padel-rietvalleirand', 'DPT Padel Rietvalleirand', 'Rietvalleirand', 'Pretoria', 'Gauteng', 1, 'Playtomic'),
  ('gayle-padel-club', 'Gayle Padel Club', 'Raslouw', 'Pretoria', 'Gauteng', null, 'Playtomic'),
  ('hartbeespoort-padel-brits', 'Hartbeespoort Padel Brits', 'Hartbeespoort', 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('padel-lab-clubview', 'Padel Lab Clubview', 'Clubview', 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('padel-lab-elardus-park', 'Padel Lab Elardus Park', 'Elardus Park', 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('padel-park-pretoria', 'Padel Park Pretoria', null, 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('padel-play-hartbeespoort', 'Padel Play Hartbeespoort', 'Hartbeespoort', 'Pretoria', 'Gauteng', 1, 'Playtomic'),
  ('play-360-rosemary-hill', 'Play 360 Rosemary Hill', 'Centurion', 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('rietondale-padel', 'Rietondale Padel', 'Rietondale', 'Pretoria', 'Gauteng', 4, 'Playtomic'),
  ('roshnee-padel', 'Roshnee Padel', 'Roshnee', 'Pretoria', 'Gauteng', 4, 'Playtomic'),
  ('team-padel-pretoria', 'Team Padel Pretoria', null, 'Pretoria', 'Gauteng', 4, 'Playtomic'),
  ('the-range-padel-erasmia', 'The Range Padel Erasmia', 'Erasmia', 'Pretoria', 'Gauteng', 2, 'Playtomic'),
  ('thrashers-padel-menlyn', 'Thrashers Padel Menlyn', 'Menlyn', 'Pretoria', 'Gauteng', 5, 'Playtomic'),
  ('u-pro-action-sports-faerieglen', 'U-Pro Action Sports Faerieglen', 'Faerieglen', 'Pretoria', 'Gauteng', 3, 'Playtomic'),
  ('u-pro-padel-atterbury-value-mart', 'U-Pro Padel Atterbury Value Mart', 'Atterbury', 'Pretoria', 'Gauteng', 4, 'Playtomic'),
  ('virgin-active-padel-groenkloof', 'Virgin Active Padel Groenkloof', 'Groenkloof', 'Pretoria', 'Gauteng', 5, 'Playtomic'),
  ('anchorage-padel-vaal', 'Anchorage Padel Vaal', 'Vaal', 'Vereeniging', 'Gauteng', 1, 'Playtomic'),
  ('emfuleni-padel', 'Emfuleni Padel', 'Vanderbijlpark', 'Vereeniging', 'Gauteng', 1, 'Playtomic'),
  ('sebenza-padel-club-vanderbijlpark', 'Sebenza Padel Club Vanderbijlpark', 'Vanderbijlpark', 'Vereeniging', 'Gauteng', 2, 'Playtomic'),
  ('ten-by-twenty-three-rivers', 'Ten by Twenty Three Rivers', 'Three Rivers', 'Vereeniging', 'Gauteng', 2, 'Playtomic'),
  ('v-town-padel', 'V-Town Padel', 'Vanderbijlpark', 'Vereeniging', 'Gauteng', 2, 'Playtomic'),
  ('africa-padel-ballito', 'Africa Padel Ballito', null, 'Ballito', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('africa-padel-kloof', 'Africa Padel Kloof', 'Kloof', 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('africa-padel-la-lucia', 'Africa Padel La Lucia', 'La Lucia', 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('africa-padel-salt-rock', 'Africa Padel Salt Rock', 'Salt Rock', 'Durban', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('al-falaah-padel', 'Al Falaah Padel', null, 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('chiltern-park', 'Chiltern Park', 'Westville', 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('dream-padel-mount-edgecombe', 'Dream Padel Mount Edgecombe', 'Mount Edgecombe', 'Durban', 'KwaZulu-Natal', 1, 'Playtomic'),
  ('eastbury-padel-phoenix', 'Eastbury Padel Phoenix', 'Phoenix', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('gayle-padel-berea', 'Gayle Padel Berea', 'Berea', 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('gayle-padel-durban-north', 'Gayle Padel Durban North', 'Durban North', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('gayle-padel-hillcrest', 'Gayle Padel Hillcrest', 'Hillcrest', 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('karibu-padel-dolphin-coast', 'Karibu Padel Dolphin Coast', 'Dolphin Coast', 'Durban', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('nex-padel', 'Nex Padel', 'Berea', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('padel-ace-westville', 'Padel Ace Westville', 'Westville', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('padel-hq-dolphin-coast', 'Padel HQ Dolphin Coast', 'Dolphin Coast', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('padel-perfect', 'Padel Perfect', null, 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('smash-padel-berea', 'Smash Padel Berea', 'Berea', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('the-padel-pros-dome', 'The Padel Pros Dome', 'Dolphin Coast', 'Durban', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('wipadel-sherwood', 'WiPadel Sherwood', 'Sherwood', 'Durban', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('the-racket-club-cotswold-downs', 'The Racket Club Cotswold Downs', 'Hillcrest', 'Hillcrest', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('velocity-gym-padel-hilton', 'Velocity Gym Padel Hilton', 'Hilton', 'Hilton', 'KwaZulu-Natal', 1, 'Playtomic'),
  ('south-coast-padel-margate', 'South Coast Padel Margate', 'Margate', 'Margate', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('net-set-padel-nottingham-road', 'Net Set Padel Nottingham Road', 'Nottingham Road', 'Nottingham Road', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('umdoni-point-sports-leisure', 'Umdoni Point Sports & Leisure', 'Pennington', 'Pennington', 'KwaZulu-Natal', 4, 'Playtomic'),
  ('next-padel-pietermaritzburg', 'Next Padel Pietermaritzburg', 'Pietermaritzburg', 'Pietermaritzburg', 'KwaZulu-Natal', 1, 'Playtomic'),
  ('padel-power-pietermaritzburg', 'Padel Power Pietermaritzburg', 'Pietermaritzburg', 'Pietermaritzburg', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('padelpmb', 'PadelPMB', 'Pietermaritzburg', 'Pietermaritzburg', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('sheppie-padel-club', 'Sheppie Padel Club', 'Port Shepstone', 'Port Shepstone', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('station-padel-sugar-village', 'Station Padel Sugar Village', 'Umhlali', 'Umhlali', 'KwaZulu-Natal', 2, 'Playtomic'),
  ('padel-nation-umhlanga', 'Padel Nation Umhlanga', null, 'Umhlanga', 'KwaZulu-Natal', 3, 'Playtomic'),
  ('virgin-active-padel-gateway', 'Virgin Active Padel Gateway', 'Gateway', 'Umhlanga', 'KwaZulu-Natal', 6, 'Playtomic'),
  ('534-padel', '534 Padel', null, 'Polokwane', 'Limpopo', null, 'Playtomic'),
  ('n1-padel-polokwane', 'N1 Padel Polokwane', null, 'Polokwane', 'Limpopo', 2, 'Playtomic'),
  ('padel-24-mbombela', 'Padel 24 Mbombela', null, 'Mbombela', 'Mpumalanga', 3, 'Playtomic'),
  ('play-360', 'Play 360', null, 'Mbombela', 'Mpumalanga', null, 'Playtomic'),
  ('padel-101', 'Padel 101', null, 'Standerton', 'Mpumalanga', null, 'Playtomic'),
  ('net-set-white-river', 'Net Set White River', null, 'White River', 'Mpumalanga', 2, 'Playtomic'),
  ('techno-padel-potchefstroom', 'Techno Padel Potchefstroom', null, 'Potchefstroom', 'North West', null, 'Playtomic'),
  ('padel-t-rustenburg', 'Padel T Rustenburg', null, 'Rustenburg', 'North West', null, 'Playtomic'),
  ('action-padel-century-city', 'Action Padel Century City', 'Century City', 'Cape Town', 'Western Cape', 2, 'Playtomic'),
  ('action-padel-diep-river', 'Action Padel Diep River', 'Diep River', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('action-padel-edgemead', 'Action Padel Edgemead', 'Edgemead', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('africa-padel-camps-bay', 'Africa Padel Camps Bay', 'Camps Bay', 'Cape Town', 'Western Cape', 5, 'Playtomic'),
  ('africa-padel-claremont', 'Africa Padel Claremont', 'Claremont', 'Cape Town', 'Western Cape', 9, 'Playtomic'),
  ('africa-padel-v-a', 'Africa Padel V&A', 'V&A Waterfront', 'Cape Town', 'Western Cape', 5, 'Playtomic'),
  ('arturf-padel-arena', 'Arturf Padel Arena', null, 'Cape Town', 'Western Cape', 6, 'Playtomic'),
  ('atlantic-padel-sunningdale', 'Atlantic Padel Sunningdale', 'Sunningdale', 'Cape Town', 'Western Cape', 4, 'Playtomic'),
  ('atlantic-padel-table-view', 'Atlantic Padel Table View', 'Table View', 'Cape Town', 'Western Cape', 2, 'Playtomic'),
  ('aura-padel-club', 'Aura Padel Club', null, 'Cape Town', 'Western Cape', 5, 'Playtomic'),
  ('bay-padel-tokai', 'Bay Padel Tokai', 'Tokai', 'Cape Town', 'Western Cape', 6, 'Playtomic'),
  ('camps-bay-retreat-padel', 'Camps Bay Retreat Padel', 'Camps Bay', 'Cape Town', 'Western Cape', 1, 'Direct'),
  ('eden-padel', 'Eden Padel', 'Durbanville', 'Cape Town', 'Western Cape', 4, 'Playtomic'),
  ('epicentre-padel', 'Epicentre Padel', null, 'Cape Town', 'Western Cape', 5, 'Playtomic'),
  ('glen-virgin-active-padel-club', 'Glen Virgin Active Padel Club', 'Clifton', 'Cape Town', 'Western Cape', 1, 'Playtomic'),
  ('kelvin-grove-newlands', 'Kelvin Grove Newlands', 'Newlands', 'Cape Town', 'Western Cape', 3, 'Direct'),
  ('lekka-padel-milnerton', 'Lekka Padel Milnerton', 'Milnerton', 'Cape Town', 'Western Cape', 2, 'Playtomic'),
  ('mount-nelson-hotel-padel', 'Mount Nelson Hotel Padel', 'Gardens', 'Cape Town', 'Western Cape', 1, 'Direct'),
  ('net-set-camps-bay-retreat', 'Net Set Camps Bay Retreat', 'Camps Bay', 'Cape Town', 'Western Cape', 1, 'Direct'),
  ('padel-365-noordhoek-emporium', 'Padel 365 Noordhoek Emporium', 'Noordhoek', 'Cape Town', 'Western Cape', 4, 'Playtomic'),
  ('padel-365-richmond-park', 'Padel 365 Richmond Park', 'Montague Gardens', 'Cape Town', 'Western Cape', 5, 'Playtomic'),
  ('padel-century-city-slipstream', 'Padel Century City Slipstream', 'Century City', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('padel-lansdowne', 'Padel Lansdowne', 'Lansdowne', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('padel-life-old-mutual-sports-club', 'Padel Life Old Mutual Sports Club', 'Pinelands', 'Cape Town', 'Western Cape', 6, 'Playtomic'),
  ('padel-milnerton-richmond', 'Padel Milnerton Richmond', 'Milnerton', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('padel-ottery', 'Padel Ottery', 'Ottery', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('padel-rondebosch', 'Padel Rondebosch', 'Rondebosch', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('padel-turfhall', 'Padel Turfhall', 'Turfhall', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('padel-5-hout-bay', 'Padel@5 Hout Bay', 'Hout Bay', 'Cape Town', 'Western Cape', 1, 'Playtomic'),
  ('point-padel-club', 'Point Padel Club', 'Point', 'Cape Town', 'Western Cape', 4, 'Playtomic'),
  ('racket-ball-club-bree-street', 'Racket+Ball Club Bree Street', 'Bree Street', 'Cape Town', 'Western Cape', 4, 'Playtomic'),
  ('rb-club-cape-town-indoor', 'RB Club Cape Town (Indoor)', 'Cape Town CBD', 'Cape Town', 'Western Cape', 4, 'Playtomic'),
  ('stadium-on-main-padel', 'Stadium on Main Padel', 'Claremont', 'Cape Town', 'Western Cape', null, 'Playtomic'),
  ('virgin-active-padel-paarden-eiland', 'Virgin Active Padel Paarden Eiland', 'Paarden Eiland', 'Cape Town', 'Western Cape', 5, 'Playtomic'),
  ('virgin-active-padel-pinehurst', 'Virgin Active Padel Pinehurst', 'Durbanville', 'Cape Town', 'Western Cape', 3, 'Playtomic'),
  ('volea-padel-kommetjie', 'Volea Padel Kommetjie', 'Kommetjie', 'Cape Town', 'Western Cape', 2, 'Playtomic'),
  ('welgemoed-padel', 'Welgemoed Padel', 'Welgemoed', 'Cape Town', 'Western Cape', 1, 'Playtomic'),
  ('garden-route-padel-george', 'Garden Route Padel George', 'Glenwood', 'George', 'Western Cape', 2, 'Playtomic'),
  ('lets-play-padel-george', 'Lets Play Padel George', 'George', 'George', 'Western Cape', 3, 'Playtomic'),
  ('telesto-tennis-academy', 'Telesto Tennis Academy', null, 'George', 'Western Cape', 2, 'Playtomic'),
  ('play-padel-hermanus-sports-club', 'Play Padel Hermanus Sports Club', 'Hermanus', 'Hermanus', 'Western Cape', 4, 'Playtomic'),
  ('livpadel-knysna', 'LivPadel Knysna', null, 'Knysna', 'Western Cape', 2, 'Playtomic'),
  ('simola-padel', 'Simola Padel', null, 'Knysna', 'Western Cape', 2, 'Playtomic'),
  ('mossel-bay-padel', 'Mossel Bay Padel', 'Mossel Bay', 'Mossel Bay', 'Western Cape', 2, 'Playtomic'),
  ('point-padel-mossel-bay', 'Point Padel Mossel Bay', 'Mossel Bay', 'Mossel Bay', 'Western Cape', 2, 'Playtomic'),
  ('padel-ace-paarl', 'Padel Ace Paarl', null, 'Paarl', 'Western Cape', 2, 'Playtomic'),
  ('val-de-vie-padel', 'Val de Vie Padel', 'Val de Vie', 'Paarl', 'Western Cape', null, 'Direct'),
  ('absolute-padel-plett', 'Absolute Padel Plett', null, 'Plettenberg Bay', 'Western Cape', 3, 'Playtomic'),
  ('africa-padel-plettenberg-bay', 'Africa Padel Plettenberg Bay', null, 'Plettenberg Bay', 'Western Cape', 2, 'Playtomic'),
  ('forest-gate-padel', 'Forest Gate Padel', null, 'Plettenberg Bay', 'Western Cape', null, 'Playtomic'),
  ('padel-365-plett-country-club', 'Padel 365 Plett Country Club', null, 'Plettenberg Bay', 'Western Cape', null, 'Playtomic'),
  ('padelx-somerset-west', 'PadelX Somerset West', 'Somerset West', 'Somerset West', 'Western Cape', null, 'Playtomic'),
  ('virgin-active-padel-lourensford', 'Virgin Active Padel Lourensford', 'Lourensford', 'Somerset West', 'Western Cape', 2, 'Playtomic'),
  ('africa-padel-van-der-stel', 'Africa Padel Van Der Stel', null, 'Stellenbosch', 'Western Cape', 4, 'Playtomic'),
  ('club-padel-stellenbosch', 'Club Padel Stellenbosch', null, 'Stellenbosch', 'Western Cape', 5, 'Playtomic'),
  ('de-zalze-golf-estate', 'De Zalze Golf Estate', null, 'Stellenbosch', 'Western Cape', 2, 'Playtomic'),
  ('hazendal-wine-estate-padel', 'Hazendal Wine Estate Padel', null, 'Stellenbosch', 'Western Cape', 1, 'Direct'),
  ('zorgvliet-wines-padel', 'Zorgvliet Wines Padel', 'Helshoogte', 'Stellenbosch', 'Western Cape', 2, 'Direct')
on conflict (id) do update set
  name = excluded.name,
  suburb = excluded.suburb,
  city = excluded.city,
  province = excluded.province,
  court_count = excluded.court_count,
  booking_platform = excluded.booking_platform;
